# -*- coding: utf-8 -*-
"""03Semana3Prog.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sbPTFdr0n5DQ3fqMV6oYUzkMIT2qHiOn

## Ejercicios de Asignación

## Ejercicio 2.1. 
Escribir un programa que le pregunte al usuario una cantidad de pesos, una tasa de interés y un número de años y muestre como resultado el monto final a obtener. La fórmula a utilizar es:

Cn = C * (1 + x/100) ^ n

Donde C es el capital inicial, x es la tasa de interés y n es el número de años a calcular.
"""

pesos = float(input("Ingrese el monto en pesos: "))
tasa = int(input("Ingrese la tasa de interés: "))
anios = int(input("Ingrese los años: "))
print(1 + tasa / 100)
print(pesos * (1 + tasa / 100))
monto_final = round(pesos * (1 + tasa / 100) ** anios, 2)

print(F"El monto final obtenido es $ {monto_final}")

"""## Ejercicio 2.2. 

Escribir un programa que convierta un valor dado en grados Fahrenheit a grados Celsius. Recordar que la fórmula para la conversión es:

F = 9/5 * C + 32.
"""

farenheit = float(input("Ingrese los grados Farenheit: "))
celsius = round((farenheit - 32) * 5 / 9, 2)

print(F"{farenheit} grados Farenheit equivalen a {celsius} grados Celsius")

"""## Ejercicio 2.3.

Escribir un programa que pregunte el nombre del usuario en la consola y después de que el usuario lo introduzca muestre por pantalla el nombre en mayúsculas y el número de caracteres que contiene en líneas distintas.
"""

nombre = input("Ingrese su nombre: ")
print(nombre.upper(), "su nombre tiene ", len(nombre), " caracteres")

"""## Ejercicios con Condicionales simples

## Ejercicio 2.4.
Escribir un programa que pregunte al usuario su edad y muestre por pantalla si es mayor de edad o no.
"""

edad = int(input("Ingrese su edad: "))

if edad >= 18:
  print("Usted es Mayor de edad!")
else:
  print("Usted es muy joven aún!")

"""## Ejercicio 2.5.

Para tributar un determinado impuesto se debe ser mayor de 16 años y tener unos ingresos superiores a $1000 mensuales.
Escribir un programa que pregunte al usuario su edad y sus ingresos mensuales y muestre por pantalla si el usuario tiene que tributar o no.

"""

edad = int(input("Ingrese su edad: "))
ingresos = float(input("Registre sus ingresos mensuales: "))

if edad > 16 and ingresos > 1000:
  print("Tiene que Tributar.")
else:
  print("No tributa")

"""## Ejercicio 2.6.
Los alumnos de un curso se han dividido en dos grupos A y B de acuerdo al sexo y el nombre. El grupo A esta formado por las mujeres con un nombre anterior a la M y los hombres con un nombre posterior a la N y el grupo B por el resto.
Escribir un programa que pregunte al usuario su nombre y sexo, y muestre por pantalla el grupo que le corresponde.

## Ejercicios con Bucles repetitivos

## Ejercicio 2.7. 

Escribir un programa que imprima todos los números pares entre dos números que se le pidan al usuario.
"""

numero_inicio = int(input("Ingrese un número: "))
numero_fin = int(input("Ingrese otro número: "))

for x in range(numero_inicio, numero_fin + 1):
  if x % 2 == 0:
    print(x)

"""## Ejercicio 2.8.

Escribir un programa que pida al usuario un número entero positivo y muestre por pantalla la cuenta desde atrás de ese número hasta cero separados por comas.
"""



"""## Ejercicio 2.9.

Escribir un programa que pida al usuario un número entero positivo y muestre por pantalla todos los números impares desde 1 hasta ese número separados por comas.
Ayuda: usar el módulo de 2 (%)
"""

numero_limite = int(input("Ingrese un número: "))

for x in range(1, numero_limite + 1):
  if x % 2 :
    print(x, end=", ")
    #print(x, sep=',', end=' ')

# Otra solución
numero_limite = int(input("Ingrese un número: "))
cadena = []

for x in range(1, numero_limite + 1):
  if x % 2 :
    cadena.append(x)

print(cadena, sep=',')

"""## Ejercicio 2.10.

Ciclos definidos

    1- Escribir un ciclo definido para imprimir por pantalla todos los números entre 10 y 20.
    2- Escribir un ciclo definido que salude por pantalla a sus cinco mejores amigos/as.
    3- Escribir un programa que use un ciclo definido con rango numérico, que pregunte los nombres de sus cinco mejores amigos/as, y los salude.
    4- Escribir un programa que use un ciclo definido con rango numérico, que pregunte los nombres de sus seis mejores amigos/as, y los salude.
    5- Escribir un programa que use un ciclo definido con rango numérico, que averigue a cuántos amigos quieren saludar, les pregunte los nombres de esos amigos/as, y los salude.

"""

# 1-
for x in range(10,20):
  print(x)

# 2-
mejores_amigas = ['María', 'Celeste', 'Nadia', 'Ayelén', 'Mónica']

for amiga in mejores_amigas:
  print(F"Hola {amiga}!, cómo estás?")

# 3-

# 4-

x=int(input())
a=int(input())
b=int(input())
y=x*a*b
print(str(y))



name = input("¿Please, Could you write your name? ")
print(name.upper() + " has " + str(len(name)) + " letters")

