# -*- coding: utf-8 -*-
"""copia de prueba.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bZ_egYKYEn03Y1eez5po1UYZ4wOwJDzX

## Programación - Ciencia de datos - Condicionales - 11/052021

### Ejercicio 1

Escribir un programa que muestre por pantalla la cadena ¡Hola Mundo!.
"""

print('¡Hola Mundo!')

"""### Ejercicio 2

Escribir un programa que almacene la cadena ¡Hola Mundo! en una variable y luego muestre por pantalla el contenido de la variable.
"""

cadena = "¡Hola Mundo!"
print(cadena)

"""### Ejercicio 3

Escribir un programa que pregunte el nombre del usuario en la consola y después de que el usuario lo introduzca muestre por pantalla la cadena ¡Hola <nombre>!, donde <nombre> es el nombre que el usuario haya introducido.
"""

nombre = input("Ingrese su nombre: ")
print(F"¡Hola!, {nombre}")

"""### Ejercicio 4

Escribir un programa que muestre por pantalla el resultado de la siguiente operación aritmética: 3 mas 2 dividido 2 por 5, todo al cuadrado.

$$ \big(\frac{3+2}{2*5}\big)^2 $$ 
"""

print( ((3 + 2) / (2 * 5)) ** 2 )

"""### Ejercicio 5

Escribir un programa que pregunte al usuario por el número de horas trabajadas y el coste por hora. Después debe mostrar por pantalla la paga que le corresponde.
"""

horas_trabajadas = int(input("Ingrese las horas trabajadas: "))
coste_hora = float(input("Ingrese el valor de cada hora: "))
print("Corresponde abonarle: $", round(horas_trabajadas * coste_hora, 2) )

"""### Ejercicio 6

Escribir un programa que lea un entero positivo, n, introducido por el usuario y después muestre en pantalla la suma de todos los enteros desde 1 hasta n. La suma de los primeros enteros positivos puede ser calculada de la siguiente forma:



$$ suma = \frac{n*(n+1)}{2} $$
"""

# Opción sin fórmula:
entero_positivo = int(input("Ingrese un número entero positivo: "))
suma = 0

while entero_positivo >= 1:
  suma += entero_positivo

  entero_positivo -= 1

print("La suma: ", suma)

# Opción usando la Fórmula 
numero_ingresado = int(input("Ingrese un número entero positivo: "))

suma = (numero_ingresado * (numero_ingresado + 1)) / 2

print("La suma: ", int(suma))

"""### Ejercicio 7

Escribir un programa que pida al usuario su peso (en kg) y estatura (en metros), calcule el índice de masa corporal y lo almacene en una variable, y muestre por pantalla la frase "Tu índice de masa corporal es <imc>" donde <imc> es el índice de masa corporal calculado redondeado con dos decimales.
"""

peso = float(input("Ingrese su peso: "))
altura = float(input("Ingrese su altura: "))
imc = peso / (altura ** 2)
imc_round = round(imc, 2)

print(F"Tu índice de masa corporal es: {imc_round}")